# Generated by Django 2.2.4 on 2019-08-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0002_auto_20190807_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(default='cf', max_length=10)),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('direccion', models.TextField(default='Ciudad')),
                ('estado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateTimeField(auto_now_add=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.FloatField()),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
        migrations.CreateModel(
            name='Encabezado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('total', models.FloatField()),
                ('numero', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.Cliente')),
                ('detalle', models.ManyToManyField(through='facturacion.Detalle', to='vehiculo.Vehiculo')),
            ],
            options={
                'verbose_name': 'Encabezado',
                'verbose_name_plural': 'Encabezados',
            },
        ),
        migrations.AddField(
            model_name='detalle',
            name='factura',
            field=models.ForeignKey(on_delete='detalle', related_name='detalle_factura', to='facturacion.Encabezado'),
        ),
        migrations.AddField(
            model_name='detalle',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='vehiculo.Vehiculo'),
        ),
    ]
